// Code generated by branchkit-gen from plugin.json `action_types`. DO NOT EDIT.
// Regenerate from the plugin directory: branchkit-gen --plugin .

package main

import "github.com/branchkit/plugin-sdk-go"

// LaunchParams is the params shape for action "apps.launch (Open App)".
type LaunchParams struct {
	AppID       string `json:"app_id"`
	NewInstance *bool  `json:"new_instance,omitempty"`
}

// HandleLaunch registers a typed handler for action "apps.launch (Open App)".
func HandleLaunch(p *branchkit.Plugin, fn func(LaunchParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "apps.launch", fn)
}

// NewWindowParams is the params shape for action "apps.new_window (New Window on This Desktop)".
type NewWindowParams struct {
	AppID string `json:"app_id"`
}

// HandleNewWindow registers a typed handler for action "apps.new_window (New Window on This Desktop)".
func HandleNewWindow(p *branchkit.Plugin, fn func(NewWindowParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "apps.new_window", fn)
}

// OpenParams is the params shape for action "apps.open (Open a Link or File)".
type OpenParams struct {
	Target string `json:"target"`
}

// HandleOpen registers a typed handler for action "apps.open (Open a Link or File)".
func HandleOpen(p *branchkit.Plugin, fn func(OpenParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "apps.open", fn)
}
